= quarkus-db2-resource-bundle

This project shows that a (some?) resource bundle(s) is (are) missing when the db2 driver is used and the application is built natively.

== Reproducer
- Start the db2 container, wait for it to be started:
+
[source,bash]
----
docker compose \
  --file local-deployment/docker-compose \
  up --detach`
----
- While the db2 container starts, take a look at link:src/main/resources/application.properties[`src/main/resources/application.properties`] and notice that the application is misconfigured; no username is defined for the datasource.
- run the application in dev mode:

[source,bash]
----
$ ./mvnw clean quarkus:dev
----
- Notice that the application throws the following exception:
----
...
2025-02-20 20:18:29,206 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': [jcc][t4][10205][11234][4.34.30] Null userid is not supported. ERRORCODE=-4461, SQLSTATE=42815
2025-02-20 20:18:29,207 ERROR [de.tur.qua.db2.res.bun.Timer] (vert.x-worker-thread-1) Error while polling timer: com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][t4][10205][11234][4.34.30] Null userid is not supported. ERRORCODE=-4461, SQLSTATE=42815
	at com.ibm.db2.jcc.am.b5.a(b5.java:810)
	at com.ibm.db2.jcc.am.b5.a(b5.java:66)
	at com.ibm.db2.jcc.am.b5.a(b5.java:116)
	at com.ibm.db2.jcc.t4.b.f(b.java:2703)
	at com.ibm.db2.jcc.t4.b.a(b.java:2710)
	at com.ibm.db2.jcc.t4.b.b(b.java:939)
	at com.ibm.db2.jcc.t4.b.a(b.java:893)
	at com.ibm.db2.jcc.t4.b.a(b.java:461)
	at com.ibm.db2.jcc.t4.b.a(b.java:434)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:372)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:259)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:215)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:491)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:117)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:225)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:580)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:561)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
----
- Build the application natively, run the native executable

[source,bash]
----
$ ./mvnw --profile native clean package && \
  target/quarkus-db2-resource-bundle-999-SNAPSHOT-runner
----
- Notice that the application throws the following exception:

----
...
2025-02-20 20:02:15,000 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': [jcc]Missing resource bundle: A resource bundle could not be found in the com.ibm.db2.jcc package for IBM Data Server Driver for JDBC and SQLJ ERRORCODE=-4461, SQLSTATE=42815
2025-02-20 20:02:15,001 ERROR [de.tur.qua.db2.res.bun.Timer] (executor-thread-1) Error while polling timer: com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc]Missing resource bundle: A resource bundle could not be found in the com.ibm.db2.jcc package for IBM Data Server Driver for JDBC and SQLJ ERRORCODE=-4461, SQLSTATE=42815
	at com.ibm.db2.jcc.am.b5.a(b5.java:810)
	at com.ibm.db2.jcc.am.b5.a(b5.java:66)
	at com.ibm.db2.jcc.am.b5.a(b5.java:116)
	at com.ibm.db2.jcc.t4.b.f(b.java:2703)
	at com.ibm.db2.jcc.t4.b.a(b.java:2710)
	at com.ibm.db2.jcc.t4.b.b(b.java:939)
	at com.ibm.db2.jcc.t4.b.a(b.java:893)
	at com.ibm.db2.jcc.t4.b.a(b.java:461)
	at com.ibm.db2.jcc.t4.b.a(b.java:434)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:372)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:259)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:215)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:491)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:117)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:225)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:580)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:561)
	at java.base@21.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
...
----

== Contributors ✨

Thanks goes to these wonderful people (https://allcontributors.org/docs/en/emoji-key[emoji key]):

++++
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<table>
  <tbody>
    <tr>
      <td align="center" valign="top" width="14.28%"><a href="https://turing85.github.io"><img src="https://avatars.githubusercontent.com/u/32584495?v=4?s=100" width="100px;" alt="Marco Bungart"/><br /><sub><b>Marco Bungart</b></sub></a><br /><a href="#code-turing85" title="Code">💻</a> <a href="#maintenance-turing85" title="Maintenance">🚧</a> <a href="#doc-turing85" title="Documentation">📖</a></td>
    </tr>
  </tbody>
</table>

<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->

<!-- ALL-CONTRIBUTORS-LIST:END -->
++++

This project follows the https://github.com/all-contributors/all-contributors[all-contributors] specification. Contributions of any kind welcome!