services:
  db2db:
    image: "docker.io/ibmcom/db2:11.5.7.0"
    privileged: true
    environment:
      - "LICENSE=accept"
      - "DB2INSTANCE=user"
      - "DB2INST1_PASSWORD=password"
      - "DBNAME=DATABASE"
    ports:
      - "50000:50000"
    volumes:
      - "./db2db/database:/database"